### PR TITLE
Add Coding Patterns and Guidelines Documentation

### PR DESCRIPTION
**Pull request by itsmdasifraza**
## Description
This PR introduces a comprehensive Coding Patterns and Guidelines document to ensure consistency, readability, and maintainability across the codebase.

## Key Highlights:

- Standardized naming conventions for variables, functions, classes, and constants.
- Emphasis on best practices, including arrow functions, destructuring, and default parameters.
- Clear examples demonstrating preferred and non-preferred approaches.
- Principles like Single Responsibility and avoiding magic numbers.
- Improved error handling patterns.

## Why this is important:

- Enhances code clarity and reduces ambiguity.
- Encourages adherence to industry best practices.
- Serves as a reference guide for both new and existing developers.
- Please review the document and share your feedback! 🚀

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build

## Have you tested locally?

- [x] 👍 yes
- [ ] 🙅 no, because I am lazy

### CODE REVIEW

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Review by Astitva877 — APPROVED** [review]

**Pull request merged**
