### PR TITLE
fix: profile-icon first letter, drag from header free space when window is shrinked

### PR DESCRIPTION
**Pull request by LordNayan**
## Description

1) Fix incorrect profile-icon first letter.
2) Fix window was not draggable from header free space when window is shrinked.
3) Fix environment right click menu.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build

## Have you tested locally?

- [x] 👍 yes
- [ ] 🙅 no, because I am lazy

### CODE REVIEW

**Comment by pratikshinde590** [comment]
### SonarQube Quality Gate Result
- **Result**: :white_check_mark: OK
- Triggered by @LordNayan on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|New reliability rating|:white_check_mark: OK|1|> 1|
|New security rating|:white_check_mark: OK|1|> 1|
|New maintainability rating|:white_check_mark: OK|1|> 1|

[View on SonarQube](https://sonar.techdomeaks.com/dashboard?id=sparrow)
###### _updated: 1/31/2024, 07:51:06 (UTC+0)_

**Review by itsmdasifraza — APPROVED** [review]

**Pull request merged**
