### PR TITLE
feat: added websocket RPC flow []

### PR DESCRIPTION
**Pull request by Astitva877**
## Description
This PR consist the RPC side of code for web  socket functionality.  #1348 
- Connect web socket function 
- Send message 
- Disconnect function

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build

## Have you tested locally?

- [x] 👍 yes
- [ ] 🙅 no, because I am lazy

### CODE REVIEW

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Review by gc-codes — APPROVED** [review]

**Review by itsmdasifraza — APPROVED** [review]

**Pull request merged**
