### PR TITLE
bug:resolved-overlapping[#2168]

### PR DESCRIPTION
**Pull request by aakashreddy-p**
## Description
I have updated the position of caution in save pop-up.
Please do not leave this blank 

## What type of PR is this? (check all applicable)
- [x] 🐛 Bug Fix 

## Have you tested locally?
- [x] 👍 yes

### CODE REVIEW

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by aakashreddy-p** [comment]
> Please attach the issue link https://github.com/actions/runner-images/issues/10636

**Review by LordNayan — APPROVED** [review]

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Pull request merged**
