### PR TITLE
[staging]  fix: Fixed folder rename and collection rename function 

### PR DESCRIPTION
**Pull request by Abhishek9503**
## Description

In this PR i have changed two functions that is folder renaming and collection renaming function which was previously called without renaming the folder and collection name so added condition that function will only called when the folder or collection is renamed also i have fixed the collection name input Ui which is not aligned with button.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build

## Have you tested locally?

- [x] 👍 yes
- [ ] 🙅 no, because I am lazy

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md

### CODE REVIEW

**Comment by punitkashyup** [comment]
Please attach the issue link

**Comment by punitkashyup** [comment]
Please attach the issue link

**Review by itsmdasifraza — APPROVED** [review]

**Comment by punitkashyup** [comment]
Please attach the issue link

**Pull request merged**
