### PR TITLE
Fix/1228/revert unsaved api red dot on backtrack

### PR DESCRIPTION
**Pull request by itsmdasifraza**
## Description
This pull request addresses the issue where the unsaved API red dot indicator persists on backtracking. The fix reverts changes that caused this undesired behavior, ensuring that the red dot indicator behaves as expected when users navigate backwards.
#1228 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build

## Have you tested locally?

- [x] 👍 yes
- [ ] 🙅 no, because I am lazy

### CODE REVIEW

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Review by Astitva877 — APPROVED** [review]

**Pull request merged**
