### PR TITLE
Fix/bugs from sprint two

### PR DESCRIPTION
**Pull request by isha-dubey**
## Description

 Issues Fixed -
1. In workspace tab "Number of collection" location in right side is not as per figma.
2. Teams Popup> Icon is written in the place of logo.
3. Newly created team should come at the top(User experience)
4. UI issue of shimmer image in workspace setting.
5. For a workspace tab> if user edit the name in "about" its not changing in "workspace setting".

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build

## Have you tested locally?

- [x] 👍 yes
- [ ] 🙅 no, because I am lazy

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md

### CODE REVIEW

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Review by gc-codes — APPROVED** [review]

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Pull request merged**
