### PR TITLE
fix :  fixed the issue 1786 

### PR DESCRIPTION
**Pull request by sahell0x**
## Description
issue : https://github.com/sparrowapp-dev/sparrow-app/issues/1786
what i changed: 
[Screencast from 2024-10-23 13-10-35.webm](https://github.com/user-attachments/assets/d5adf096-987b-4ceb-a29e-4323f2a1b31e)

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build

## Have you tested locally?

- [x] 👍 yes
- [ ] 🙅 no, because I am lazy

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md

### CODE REVIEW

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by sahell0x** [comment]
> Please attach the issue link
where to attach issue link please make it more clear for me sir

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Pull request closed without merging**
