### PR TITLE
Release--Version 1.1.0

### PR DESCRIPTION
**Pull request by punitkashyup**
## Description

Please do not leave this blank 

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [x] 🔥 Performance Improvements
- [ ] ✅ Test
- [x] 🤖 Build

## Have you tested locally?

- [x] 👍 yes
- [ ] 🙅 no, because I am lazy

## Any Known issue?

- Deep Linking(Browser to App redirect) only works if the default install directory is selected. If the user changes the location then Auth breaks [Windows]
- If the user does not have a default email app it is opening the browser on mailto links. [Universal]
- Extra window with white screen appearing after login. [Windows]
- Refreshing the page at forgot password OTP screen does not invalidate the OTP.
- On leaving the team the home screen appears blank. A new team has to be selected manually from the left side pane.
- Deleted workspace sometimes appears in the "Activate new workspace" dropdown.
- Response is not rendered automatically for huge JSON/HTML responses. Need to click on the response editor to render after scroll.

### CODE REVIEW

**Review by LordNayan — APPROVED** [review]

**Comment by punitkashyup** [comment]
### SonarQube Quality Gate Result
- **Result**: :white_check_mark: OK
- Triggered by @punitkashyup on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|New reliability rating|:white_check_mark: OK|1|> 1|
|New security rating|:white_check_mark: OK|1|> 1|
|New maintainability rating|:white_check_mark: OK|1|> 1|

[View on SonarQube](https://sonar.techdomeaks.com/dashboard?id=sparrow)
###### _updated: 3/1/2024, 17:33:41 (UTC+0)_

**Review by LordNayan — APPROVED** [review]

**Review by LordNayan — APPROVED** [review]
Looks good for 1st release. - Nayan

**Pull request merged**
