### PR TITLE
fix: Fixed bug from development board

### PR DESCRIPTION
**Pull request by Abhishek9503**
## Description
#1122 
#1124 

In this PR i have solved bug from development board 
1. Updated dynamic height of sidebar and collection list 
2. Removed two toast message of update available

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build

## Have you tested locally?

- [x] 👍 yes
- [ ] 🙅 no, because I am lazy

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md

### CODE REVIEW

**Comment by itsmdasifraza** [comment]
Don't think this much code is required, setting height to 100% or using flexbox will automatically adjust the component height, no need to put hard code values in calc function.

**Comment by itsmdasifraza** [comment]
```
    {#if collectionFilter.length > 0}
              <List
                bind:scrollList
                height={updaterVisible && updateAvailable ? "calc(100vh - 220px)" : "calc(100vh - 170px)"}
                classProps={"pb-2 pe-1"}
              >
                {#each collectionFilter as col}
	@@ -356,7 +359,7 @@
            {:else}
              <List
                bind:scrollList
                height={updaterVisible && updateAvailable ? "calc(100vh - 220px)" : "calc(100vh - 170px)"}
                classProps={"pb-2 pe-1"}
              >
                <p
	@@ -369,7 +372,7 @@
          {:else}
            <List
              bind:scrollList
              height={updaterVisible && updateAvailable ? "calc(100vh - 220px)" : "calc(100vh - 170px)"}
              classProps={"pb-2 pe-1"}
            >
```

**Comment by Abhishek9503** [comment]
> Don't think this much code is required, setting height to 100% or using flexbox will automatically adjust the component height, no need to put hard code values in calc function.

I have tried using height 100% and  flexbox it doesn't work , i have asked ketan too ,  you can try once , if possible...

**Review by itsmdasifraza — CHANGES_REQUESTED** [review]
Lets connect with other developers also and give a complete fix.

**Pull request closed without merging**
