### PR TITLE
fix #367

### LINKED ISSUE #367: UI issue in Sending invite popup at team level for editor/member
### **🐛 Bug Report**

UI issue in Sending invite popup at team level for editor 

**Steps to reproduce:**

- Login to sparrow and at team click on invite 
- Enter mail id and select editor or member and open dropdown for workspace selection

**Expected Behaviour:** All the checkboxes and workspaces name should aligned
**Actual Behaviour:** workspace selection dropdown has some UI issue - check boxes and workspaces name not aligned 

Screenshot 2024-02-25 at 6 48 54 PM

### PR DESCRIPTION
**Pull request by parthdalaltech**
## Description
Fixed:
https://github.com/sparrowapp-dev/sparrow-app/issues/367

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build

## Have you tested locally?

- [ ] 👍 yes
- [ ] 🙅 no, because I am lazy

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md

### CODE REVIEW

**Comment by punitkashyup** [comment]
### SonarQube Quality Gate Result
- **Result**: :white_check_mark: OK
- Triggered by @parthdalaltech on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|New reliability rating|:white_check_mark: OK|1|> 1|
|New security rating|:white_check_mark: OK|1|> 1|
|New maintainability rating|:white_check_mark: OK|1|> 1|

[View on SonarQube](https://sonar.techdomeaks.com/dashboard?id=sparrow)
###### _updated: 2/26/2024, 11:16:11 (UTC+0)_

**Review by LordNayan — APPROVED** [review]

**Pull request merged**
