### PR TITLE
fix : wraped async function in call back wth IIFE

### PR DESCRIPTION
**Pull request by sahell0x**
Issue link

https://github.com/sparrowapp-dev/sparrow-app/issues/1829

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build

## Have you tested locally?

- [x] 👍 yes
- [ ] 🙅 no, because I am lazy

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md

### CODE REVIEW

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by sahell0x** [comment]
> Please attach the issue link

https://github.com/sparrowapp-dev/sparrow-app/issues/1829

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by sahell0x** [comment]
> Please attach the issue link

Where??

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Pull request closed without merging**
